spring:
  application:
    name: hello
    datasource:
      driverClassName: org.h2.Driver
      url:  jdbc:h2:mem:hello_db
      username: root
      password: root
      druid:
        initial-size: 2
        max-active: 10
    jpa:
      show-sql: true
      format_sql: true
      hibernate:
        ddl-auto: update
        use-new-id-generator-mappings:  true
      database-platform:  org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**