spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:hello_db
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
