spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mariadb://myddbb:3306/hello_db
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

# LOGGING  logging.file or logging.path
logging:
  file: ./logs/hello-db.log
security:
  oauth2:
    resource:
      prefer-token-info:
#  path: /app/logs
#  syslog:
#    host: syslog.change.hostname
#    facility: LOCAL1
