spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:hello_db
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  cache:
    jcache:
      config: ehcache3.xml

# mariadb
#jdbc:mariadb://myddbb:3306/hello_db
#org.mariadb.jdbc.Driver
#org.hibernate.dialect.MySQL5InnoDBDialect

# LOGGING  logging.file or logging.path
logging:
  file: ./logs/hello-db.log
security:
  oauth2:
    resource:
      prefer-token-info:
#  path: /app/logs
#  syslog:
#    host: syslog.change.hostname
#    facility: LOCAL1
