spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /WEB-INF/page/
      suffix: .jsp
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
  cache:
    jcache:
      config: ehcache3.xml